# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQ36xs5WV5Xl6jm6KgNgQosCeSU0tPMq
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# Load both models
#vehicle_model = tf.keras.models.load_model("model_4.h5")
#overload_model = tf.keras.models.load_model("overload_model_4.h5")

# Load both models using the new Keras format
vehicle_model = tf.keras.models.load_model("model_4.keras")
overload_model = tf.keras.models.load_model("overload_model_4.keras")


# Define vehicle classes
classes = ["bodaboda", "bus", "matatu", "tuktuk"]

# Image preprocessing function
def preprocess_image(image):
    image = image.resize((224, 224))  # Resize to match model input
    image = np.array(image) / 255.0   # Normalize pixel values
    image = np.expand_dims(image, axis=0)  # Add batch dimension
    return image

# Function to classify vehicle & detect overload
def classify_vehicle(image):
    vehicle_pred = vehicle_model.predict(image)
    vehicle_class = np.argmax(vehicle_pred)  # Get class with highest probability

    overload_pred = overload_model.predict(image)
    overloaded = overload_pred[0][0] > 0.5  # Threshold for overloaded

    vehicle_name = classes[vehicle_class]

    if overloaded:
        return f"🚨 Overloaded {vehicle_name}"
    else:
        return f"✅ Normal {vehicle_name}"

# Streamlit UI
st.title("Vehicle Classification & Overload Detection")
st.write("Upload an image to classify the vehicle and check if it's overloaded.")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_column_width=True)

    # Preprocess and classify
    processed_image = preprocess_image(image)
    result = classify_vehicle(processed_image)

    st.success(result)